.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = app-dev-debian
TEMPLATE_DESCRIPTION = App - Dev - Debian
TEMPLATE_VERSION     = 2.0.7
TEMPLATE_MOUNT_DIR   = /srv/app
TEMPLATE_PLATFORMS   = vagrant.virtualbox docker
