.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = dab
TEMPLATE_DESCRIPTION = Debian Appliance Builder
TEMPLATE_VERSION     = 3.0.9
TEMPLATE_MOUNT_DIR   = /srv/template
TEMPLATE_PLATFORMS   = vagrant.virtualbox
