.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = dab
TEMPLATE_DESCRIPTION = Dab
TEMPLATE_VERSION     = 5.1.0
TEMPLATE_MOUNT_DIR   = /srv/template
TEMPLATE_PLATFORMS   = vagrant.virtualbox
