# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 2.0.2'

Vagrant.configure('2') do |config|

  # Ssh
  config.ssh.username      = 'app'
  config.ssh.forward_agent = true

  # Vm
  config.vm.box      = 'app-dev-debian'
  config.vm.hostname = 'app-dev-debian.2.vagrant.virtualbox'
  config.vm.network    'private_network', type: 'dhcp'
  config.vm.define     'localhost' do |localhost| end

  config.vm.synced_folder '..', '/srv/app'

  # Vm - Provider
  config.vm.provider 'virtualbox'

end
