---

- hosts: localhost

  vars:

    ######################
    # Manala - Oh My Zsh #
    ######################

    manala_ohmyzsh_users:
      - user:     manala
        group:    manala
        template: users/default.dev.j2
        config:
          - "[ -d /srv ] && cd /srv"

  roles:
    - role: manala.git
    - role: manala.zsh
    - role: manala.oh-my-zsh
