.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = development-debian
TEMPLATE_DESCRIPTION = Development - Debian
TEMPLATE_VERSION     = 4.0.0
TEMPLATE_MOUNT_DIR   = /srv
TEMPLATE_PLATFORMS   = vagrant.virtualbox docker
