.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE                = devbox-debian-9
TEMPLATE_DESCRIPTION    = Manala Devbox - Debian 9
TEMPLATE_VERSION        = 1.0.0
TEMPLATE_VERSION_LATEST = true
TEMPLATE_MOUNT_DIR      = /srv
TEMPLATE_PLATFORMS      = vagrant.virtualbox docker
