.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = packer
TEMPLATE_DESCRIPTION = Packer
TEMPLATE_VERSION     = 1.2.2
TEMPLATE_MOUNT_DIR   = /srv
TEMPLATE_PLATFORMS   = vagrant.virtualbox
