.SILENT:

##########
# Manala #
##########

include .manala/make/Makefile

############
# Template #
############

TEMPLATE             = devbox-debian
TEMPLATE_DESCRIPTION = Devbox - Debian
TEMPLATE_VERSION     = 4.0.0
TEMPLATE_MOUNT_DIR   = /srv
TEMPLATE_PLATFORMS   = vagrant.virtualbox docker
