# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  # Vm
  config.vm.box      = 'dab'
  config.vm.hostname = 'dab.vagrant.virtualbox'

  config.vm.synced_folder '..', '/srv/template'

end
