---

- hosts: localhost

  vars:

    #################
    # Manala - Apt #
    #################

    manala_apt_preferences:
      - thefuck@manala
      - gitsplit@manala
      - exa@manala
      - httpie@manala
      - git@backports

    manala_apt_packages:
      - debfoster
      - rsync
      - curl
      - htop
      - less
      - ssl-cert
      - thefuck
      - gitsplit
      - exa
      - httpie

    #################
    # Manala - Motd #
    #################

    manala_motd_template: template/manala.j2
    manala_motd_message:  "{{ template_description }} - {{ template_version }}"

    ################
    # Manala - Git #
    ################

    manala_git_config_template: config/default.dev.j2

    #################
    # Manala - Sudo #
    #################

    manala_sudo_sudoers_exclusive: true
    manala_sudo_sudoers:
      - file: manala
        config:
          - manala: 'ALL=(ALL) NOPASSWD:ALL'

    #####################
    # Manala - Accounts #
    #####################

    manala_accounts_groups:
      - group:  docker
        system: true
      - group: manala
        gid:   1000

    manala_accounts_users:
      - user:     manala
        uid:      1000
        shell:    /bin/bash
        password: $1$hVMBHhKk$4zC4YK.KRk3Vy9fmLd7681 # Empty password generated by "mkpasswd -s -m md5"
        group:    manala
        groups:
          - sudo
          - docker
        authorized_keys:
          - "{{ lookup('url', 'https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub') }}"

    ####################
    # Manala - Ohmyzsh #
    ####################

    manala_ohmyzsh_users:
      - user:     manala
        group:    manala
        template: users/default.dev.j2
        config:
          - "[ -d /srv ] && cd /srv"

    ################
    # Manala - Vim #
    ################

    manala_vim_config_template: config/default.dev.j2

    ####################
    # Manala - Locales #
    ####################

    manala_locales_codes:
      - code:  en_US.UTF-8
        state: absent

    manala_locales_codes_default: C.UTF-8

    ################
    # Manala - Ssh #
    ################

    # Replace by direct config as soon as manala.ssh role is ready for stretch
    manala_ssh_config_sshd_template: config/sshd/default.dev.j2
    #manala_ssh_config_sshd:
    #  - Key: value

    ####################
    # Manala - Ansible #
    ####################

    manala_ansible_config:
      - defaults:
          - force_color: 1
          - stdout_callback: skippy
          - display_skipped_hosts: false
          - system_warnings: false
          - deprecation_warnings: false
          - command_warnings: false
          - retry_files_enabled: false

    manala_ansible_hosts:
      - localhost

    manala_ansible_host_vars:
      - file: localhost.yaml
        vars:
          - ansible_connection: local
          - ansible_become: true

  roles:
    - role: manala.apt
    - role: manala.motd
    - role: manala.git
    - role: manala.zsh
    - role: manala.sudo
    - role: manala.accounts
    - role: manala.ohmyzsh
    - role: manala.vim
    - role: manala.locales
    - role: manala.ssh
    - role: manala.make
    - role: manala.ansible
